
#                                        #
#   Pumpkin Smash | Main Configuration   #
#             By Redraskal               #
#                                        #


# If for whatever reason you hate the skull texture with a passion, change it here!
ghost-skull-hash: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjhkMjE4MzY0MDIxOGFiMzMwYWM1NmQyYWFiN2UyOWE5NzkwYTU0NWY2OTE2MTllMzg1NzhlYTRhNjlhZTBiNiJ9fX0="


#
#   Thanks for downloading!
#     Make sure to leave a review on the plugin,
#     and feel free to contact me in a DM or on the resource thread
#     about any bugs or features you would like fixed/implemented!
#
#         ◎[▪‿▪]◎
#