
#                                             #
#   GhostScavengerHunt | Main Configuration   #
#                 By Redraskal                #
#                                             #


# Runs the specified console command(s)
# for when a player finds all the ghosts.
#
#  Placeholders:
#    {name} - Player's Username
#    {uuid} - Player's UUID
#    {total} - Total Ghosts Found
reward-commands:
  - "say {name} just found all the ghosts!"
  - "eco give {name} 1000"

# Runs the specified console command(s)
# for when a player finds the specified
# amount of ghosts.
#
#  Placeholders are above.
single-reward-commands:
  1:
    - "say {name} has started the Ghost Scavenger Hunt!"
  5:
    - "say {name} is half way there! (5/{total})"


# If you want to change the ghost skull texture,
# you might as well make the armor color fit! :D
#
# Here's the color picker!
#   https://www.google.com/search?q=hex+color+picker
#
# Copy the value with the # at the beginning
ghost-armor-color: "#ffffff"

# If for whatever reason you hate the skull texture with a passion, change it here!
ghost-skull-hash: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjhkMjE4MzY0MDIxOGFiMzMwYWM1NmQyYWFiN2UyOWE5NzkwYTU0NWY2OTE2MTllMzg1NzhlYTRhNjlhZTBiNiJ9fX0="

# You are able to toggle the ghost animation here.
enable-ghost-animation: true

#
#   Thanks for downloading!
#     Make sure to leave a review on the plugin,
#     and feel free to contact me in a DM or on the resource thread
#     about any bugs or features you would like fixed/implemented!
#
#         ◎[▪‿▪]◎
#